function side_by_side_numdiff_demos(struct_of_inputs,hstart,num_steps,numdiff_func,...
                                    default_figsize)
    arguments
        struct_of_inputs;
        hstart;
        num_steps;
        numdiff_func;
        default_figsize.x=0;
        default_figsize.y=0;
        default_figsize.width=300;
        default_figsize.height=240;
    end
    struct_fields = fields(struct_of_inputs);
    n_plots = length(struct_fields);
    fig_width = default_figsize.width*n_plots + 40*(n_plots-1);
    disp(fig_width)
    figure('Units', 'points',...
           'OuterPosition',[default_figsize.x default_figsize.y fig_width default_figsize.height]...
           )
    tiledlayout(1,num_steps,'TileSpacing','compact')  %('Position', [default_figsize.x default_figsize.y default_figsize.width*n_plots default_figsize.height]);
    for j = 1:n_plots
        nexttile
        cur_example = struct_of_inputs.(struct_fields{j});
        demo_various_h_values(cur_example.f,...
                              cur_example.deriv_of_f,...
                              cur_example.x,...
                              hstart,num_steps,...
                              numdiff_func,...
                              is_tiled=logical(1),...
                              title=cur_example.title...
                             );
                             %subplot_ydim=1,...
                             %subplot_xdim=num_steps,...
                             %subplot_index=j,...
    end
end
    
